# Generated by Django 5.0.2 on 2024-03-22 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_cpuntries_alter_cities_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902998)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902998)),
        ),
        migrations.AlterField(
            model_name='cpuntries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902998)),
        ),
        migrations.AlterField(
            model_name='cpuntries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902998)),
        ),
        migrations.AlterField(
            model_name='departments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902998)),
        ),
        migrations.AlterField(
            model_name='departments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902998)),
        ),
        migrations.AlterField(
            model_name='identification_types',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902490)),
        ),
        migrations.AlterField(
            model_name='identification_types',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 902490)),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 901248)),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 901248)),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 901248)),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 901248)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 901248)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 8, 18, 901248)),
        ),
    ]
