# Generated by Django 5.0.2 on 2024-04-27 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='clienteproducto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AddField(
            model_name='clienteproducto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteproducto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AddField(
            model_name='tipotransaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AddField(
            model_name='tipotransaccion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipotransaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 20, 6, 512748)),
        ),
    ]
