# Generated by Django 5.0.2 on 2024-03-18 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_person_created_at_alter_person_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('id_dept', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('id_country', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identification_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('id_person', models.IntegerField()),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739)),
        ),
        migrations.AlterField(
            model_name='person',
            name='ident_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 571739)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 556115)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 25, 16, 556115)),
        ),
    ]
